id: P442EE78E
initial_creation_type: input
source_metadata:
  title: Religious history by Nyang ral Nyima od zer (1124–1192)
  author: nyang ral nyi ma od zer/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2020-11-07); no page numbers, unrevised, no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre; This text was published by Tibet People's
    Publishing House (Xizang Renmin Chubanshe) (src)
  - Text input:unspecified
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2398
  bases:
    96df:
      title: Religious history by Nyang ral Nyima od zer (1124–1192)
      order: 1
      base_file: 96df.txt
created_at: '2022-04-15T18:30:32.488678'
last_modified_at: '2022-04-15T18:30:32.488687'
quality: null
